name: Keep Backend Awake

# Every 10 minutes
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl backend health
        run: |
          curl --fail https://kill-tracker-backend-production.up.railway.app/healthz \
            -H "Accept: application/json" \
            || echo "⚠️ Backend health check failed"
